### PR TITLE
run `get_compiler_cmd` earlier, to error if not found

### PR DESCRIPTION
**Pull request by sjkelly**
Closes: #677, #714, #716, #727

In many scenarios a default user shell may not have access to a compiler. The current behavior runs the checks after compiling the sysimg, which may take many minutes. This moves the check earlier so that this error happens earlier. It also splits the `cmd` and `args` such that it may be re-used or potentially altered by a user.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Why is the diff so big here? I think this should be a very small PR, right? Just call `get_compiler_cmd()` at the beginning of `create_sysimage` and `create_app`.

**Comment by sjkelly** [comment]
Yeah, I suppose that way is simpler... You are doing the work twice, but it is simple work.

**Comment by DilumAluthge** [comment]
Yeah, it's relatively simple work, and it doesn't take very long to do (especially relative to how long building the sysimage will take), so I think it's okay to do that work twice.

**Comment by DilumAluthge** [comment]
Closing in favor of #770

**Pull request closed without merging**
