### PR TITLE
WIP: Add `download_compiler` function to optionally download compilers

### PR DESCRIPTION
**Pull request by DilumAluthge**
This pull request adds the function `PackageCompiler.download_compiler`.

Running `PackageCompiler.download_compiler()` on 64-bit Linux or macOS will download Clang and set `ENV["JULIA_CC"]` to the path of the downloaded compiler.

### CODE REVIEW

**Comment by KristofferC** [comment]
Isn't there a jll for Clang? I know there are BB builds of Clang at least so we should use those for sure.

**Comment by DilumAluthge** [comment]
> Isn't there a jll for Clang? I know there are BB builds of Clang at least so we should use those for sure.

I had no idea there was a JLL for Clang - hence my attempt to use the official binaries.

We should definitely use Clang_jll if it exists and works.

Unfortunately, googling `Clang_jll` only brings up this: https://github.com/KristofferC/Clang_jll.jl

And I thought I remembered you saying on Slack that your Clang_jll experiment didn't work?

**Comment by KristofferC** [comment]
It didn't work on Windows :P

**Comment by DilumAluthge** [comment]
Ahhh. I see. Well now we have a working solution on Windows! The trick is to get it working on other platforms.

Did you get your `Clang_jll` working with the `PackageCompiler` test suite on macOS and Linux? I kept getting issues with clang trying (and failing) to find to `libtinfo`.

**Pull request closed without merging**
