### PR TITLE
Add a check for a package's __init__ being called appropriately

### PR DESCRIPTION
**Pull request by IanButterworth**
We're seeing odd behavior with `__init__()` in a dep being called multiple times during sysimage precompilation.

Just adding checks to see if it's reproducible here.

cc. @octogonapus

### CODE REVIEW

**Comment by KristofferC** [comment]
(1.6 is known to fail)

**Comment by IanButterworth** [comment]
The nightly failures are on master too

**Comment by IanButterworth** [comment]
Ok, our issue isn't replicated here, but perhaps these tests are worth adding?

**Comment by KristofferC** [comment]
It just seem so arbitrary. Until there is something showing that there is something going on with the init functions and that this has something to do with PackageCompiler, I'm a bit hesitant in adding this.

**Comment by IanButterworth** [comment]
ok! We're still trying to figure out what's happening.

I thought PackageCompiler took over when `__init__()`s were run, so thought guaranteeing that they're run exactly once (which the julia docs guarantee) was worth testing. Or perhaps the historical issues I'm vaguely thinking of were fixed in base.

**Comment by Octogonapus** [comment]
@IanButterworth This turned out to not be an issue, I think we should close this PR

**Pull request closed without merging**
