### PR TITLE
remove use of jl_set_value on 1.9. fix UndefVarError for new nightly error formatting

### LINKED ISSUE #708: nightly (1.9) tests failing
https://github.com/JuliaLang/PackageCompiler.jl/runs/7175757050?check_suite_focus=true#step:4:341
```
/home/runner/work/PackageCompiler.jl/PackageCompiler.jl/src/embedding_wrapper.c: In function ‘main’:
/home/runner/work/PackageCompiler.jl/PackageCompiler.jl/src/embedding_wrapper.c:107:5: warning: implicit declaration of function ‘jl_set_global’; did you mean ‘jl_get_global’? [-Wimplicit-function-declaration]
  107 |     jl_set_global(jl_base_module, jl_symbol("PROGRAM_FILE"), firstarg);
      |     ^~~~~~~~~~~~~
      |     jl_get_global
```

It appears `jl_set_global` was removed in https://github.com/JuliaLang/julia/pull/44753: @vtjnash is this considered a breaking API change?

### PR DESCRIPTION
**Pull request by simonbyrne**
Fixes #708 (I hope).

@vtjnash is this the correct usage?

### CODE REVIEW

**Comment by vtjnash** [comment]
It might be better to call jl_f_setglobal, but this does look the same

**Comment by simonbyrne** [comment]
Error appears to now be
```
ERROR: LoadError: MethodError: no method matching active_module()
You may have intended to import Base.active_module
The applicable method may be too new: running in world age 17748, while current world is 17759.

Closest candidates are:
  active_module() (method too new to be called from this world context.)
   @ REPL /opt/hostedtoolcache/julia/nightly/x64/share/julia/stdlib/v1.9/REPL/src/REPL.jl:494
  active_module(::REPL.REPLDisplay) (method too new to be called from this world context.)
   @ REPL /opt/hostedtoolcache/julia/nightly/x64/share/julia/stdlib/v1.9/REPL/src/REPL.jl:500
  active_module(::REPL.LineEditREPL) (method too new to be called from this world context.)
   @ REPL /opt/hostedtoolcache/julia/nightly/x64/share/julia/stdlib/v1.9/REPL/src/REPL.jl:498
  ...

Stacktrace:
  [1] active_module()
    @ Base ./show.jl:488
  [2] show_type_name(io::IOContext{IOBuffer}, tn::Core.TypeName)
    @ Base ./show.jl:1029
  [3] show_datatype(io::IOContext{IOBuffer}, x::DataType, wheres::Vector{TypeVar})
    @ Base ./show.jl:1082
```

**Comment by simonbyrne** [comment]
This might be due to https://github.com/JuliaLang/julia/pull/45838? @aviatesk Any suggestions on what we might be able to do here?

**Comment by IanButterworth** [comment]
bump @aviatesk

**Comment by KristofferC** [comment]
> Error appears to now be

Should be fixed via https://github.com/JuliaLang/julia/pull/46866

**Comment by simonbyrne** [comment]
This line is failing on Windows 1.7:
https://github.com/JuliaLang/PackageCompiler.jl/blob/5b3b07cdf24558e7528fe61ac16280ac0b88ceb7/test/runtests.jl#L76

**Comment by IanButterworth** [comment]
pushed fix for test breakage due to https://github.com/JuliaLang/julia/pull/47077

**Comment by IanButterworth** [comment]
RTM? The macos 1.8 runner is hanging on master too

**Comment by IanButterworth** [comment]
I'm going to merge given the discussion above and that tests pass on nightly now

**Pull request merged**
