### PR TITLE
Pass CPU targets as cmdline args

### LINKED ISSUE #790: With 1.9.0-beta4, sysimages aren't built for the specified `JULIA_CPU_TARGET`
Src OS: Linux (WSL and native), CPU: znver3
Target OS: Linux, CPU: znver2
Julia: v1.9.0-beta4
PackageCompiler: 2.1.5 (throws error) and 2.1.2 (relocates, but it doesn't mention pkgimages flag at all)

----

While building the sysimage with 1.9.0-beta4, even with `cpu_target = "generic;sandybridge,-xsaveopt,clone_all;haswell,-rdrnd,base(1)"`, the sysimage builds only for the "native" target.
So, when this sysimage is relocated to another machine, it fails to start with `ERROR: Unable to find compatible target in system image.` error

When I printed out the cmd returned by addenv, it indicated setting of JULIA_CPU_TARGET var.
This however, isn't an issue when `--pkgimages` flag isn't mentioned and `--cpu-target` is passed explicitly, i.e. what v2.1.2 does.

With
<details>

<summary>sysimage-metadata.patch (by @staticfloat)</summary>

```
diff --git a/src/processor.cpp b/src/processor.cpp
index 13b40ec4f7..accbff5469 100644
--- a/src/processor.cpp
+++ b/src/processor.cpp
@@ -770,12 +770,16 @@ static inline SysimgMatch match_sysimg_targets(S &&sysimg, T &&target, F &&max_v
     SysimgMatch match;
     bool match_name = false;
     int feature_size = 0;
+    jl_printf(JL_STDERR, "target.name: %s\n", target.name.c_str());
+    jl_printf(JL_STDERR, "sysimg.size(): %d\n", sysimg.size());
     for (uint32_t i = 0; i < sysimg.size(); i++) {
         auto &imgt = sysimg[i];
+        jl_printf(JL_STDERR, "[%d]: %s\n", i, imgt.name.c_str());
         if (!(imgt.en.features & target.dis.features).empty()) {
             // Check sysimg enabled features against runtime disabled features
             // This is valid (and all what we can do)
             // even if one or both of the targets are unknown.
+            jl_printf(JL_STDERR, "continue 1\n");
             continue;
         }
         if (imgt.name == target.name) {
@@ -786,6 +790,7 @@ static inline SysimgMatch match_sysimg_targets(S &&sysimg, T &&target, F &&max_v
             }
         }
         else if (match_name) {
+            jl_printf(JL_STDERR, "continue 2 (match_name: %d)\n", match_name);
             continue;
         }
         int new_vsz = max_vector_size(imgt.en.features);

```
 
</details> 
to print out the metadata and
<p>
<details>

<summary>cmdline.patch</summary>

```
diff --git a/src/processor.cpp b/src/processor.cpp
index 13b40ec4f7..9b6c850e65 100644
--- a/src/processor.cpp
+++ b/src/processor.cpp
@@ -734,6 +734,12 @@ static inline jl_image_fptrs_t parse_sysimg(void *hdl, F &&callback)
 template<typename T>
 static inline void check_cmdline(T &&cmdline, bool imaging)
 {
+    jl_printf(JL_STDERR, "Imaging:, %d\n", imaging);
+    jl_printf(JL_STDERR, "cmdline size, %d\n", cmdline.size());
+    for(uint32_t i = 0; i < cmdline.size(); i++) {
+        jl_printf(JL_STDERR,"CMDLINE: [%d]: Flags: %d, Name: %s\n", i, cmdline[i].en.flags, cmdline[i].name.c_str());
+    }
+
     assert(cmdline.size() > 0);
     // It's unclear what does specifying multiple target when not generating
     // sysimg means. Make it an error for now.
```
</details>  to print out the cmdline options, I could see that it indeed ignores the cpu_target in >2.1.2 versions.

<p>

The outputs for both versions of PackageCompiler:
<details>
<summary>The output for PackageCompiler@2.1.2</summary>

```julia
julia> cpu_target = "generic;sandybridge,-xsaveopt,clone_all;haswell,-rdrnd,base(1)"
julia> PackageCompiler.create_sysimage(; sysimage_path="test_212.so", cpu_target)
target.name: znver3
sysimg.size(): 3
[0]: generic
[1]: sandybridge
[2]: haswell
Imaging:, 0
cmdline size, 1
CMDLINE: [0]: Flags: 0, Name: native
target.name: znver3  -----,
sysimg.size(): 1          |--- These 3 lines repeat 8 more times.
[0]: znver3          -----'
target.name: znver3
sysimg.size(): 3
[0]: generic
[1]: sandybridge
[2]: haswell
Imaging:, 0
cmdline size, 1
CMDLINE: [0]: Flags: 0, Name: native
target.name: generic
sysimg.size(): 3
[0]: generic
[1]: sandybridge
continue 1
[2]: haswell
continue 1
Imaging:, 1
cmdline size, 3
CMDLINE: [0]: Flags: 0, Name: generic
CMDLINE: [1]: Flags: 2, Name: sandybridge
CMDLINE: [2]: Flags: 0, Name: haswell
✔ [02m:39s] PackageCompiler: compiling incremental system image
```
</details>

<details>

<summary>The output for PackageCompiler@2.1.5</summary>

```julia
julia> cpu_target = "generic;sandybridge,-xsaveopt,clone_all;haswell,-rdrnd,base(1)"
julia> PackageCompiler.create_sysimage(; sysimage_path="test_215.so", cpu_target)
target.name: znver3
sysimg.size(): 3
[0]: generic
[1]: sandybridge
[2]: haswell
Imaging:, 0
cmdline size, 1
CMDLINE: [0]: Flags: 0, Name: native
target.name: znver3
sysimg.size(): 3
[0]: generic
[1]: sandybridge
[2]: haswell
Imaging:, 0
cmdline size, 1
CMDLINE: [0]: Flags: 0, Name: native
target.name: znver3
sysimg.size(): 3
[0]: generic
[1]: sandybridge
[2]: haswell
Imaging:, 0
cmdline size, 1
CMDLINE: [0]: Flags: 0, Name: native
✔ [02m:40s] PackageCompiler: compiling incremental system image
```
</details>

### PR DESCRIPTION
**Pull request by ven-k**
- Fixes #790 
- JULIA_CPU_TARGETS are ignored while building sysimage 1.9-rc2
- Sysimages built with CPU targets as env var, tend to ignore them and result segfaults,  when relocated to the target machine
 (See[^1]) (On Julia#master and Julia#backports-release-1.9)
- I've locally tested the PR against Julia binary[^2] associated with latest commit[^3] on Backport to 1.9 PR

[^1]: https://github.com/JuliaLang/julia/pull/48809#issuecomment-1505546852
[^2]: https://buildkite.com/organizations/julialang/pipelines/julia-release-1-dot-9/builds/175/jobs/01878fbd-b60d-4609-90a7-af65eb2e8bcb/artifacts/0187900b-8624-4214-9fae-c1b8247fc16d
[^3]:https://github.com/JuliaLang/julia/commit/00334655d2c46da4693d41a0d69fa9a089a71df4

### CODE REVIEW

**Comment by ven-k** [comment]
- Once the next release of 1.9.0-* is out, will re-run the corr. tests.

- The failure[^1] on 1.10-dev is unrelated
```julia
filter = false: Error During Test at D:\a\PackageCompiler.jl\PackageCompiler.jl\test\runtests.jl:80
  Got exception outside of a @test
  Unable to automatically download/install artifact 'fooifier' from sources listed in 'C:\Users\runneradmin\AppData\Local\Temp\jl_kTjrxv\MyApp\Artifacts.toml'.
  Sources attempted:
  - https://pkg.julialang.org/artifact/d61f806c76b57e54f343634c5219d00d4c81b077
      Error: RequestError: HTTP/1.1 404 Not Found while requesting https://pkg.julialang.org/artifact/d61f806c76b57e54f343634c5219d00d4c81b077
  - https://github.com/staticfloat/small_bin/raw/master/libfoo/libfoo.x86_64-w64-mingw32.tar.gz
      Error: Tree Hash Mismatch!
    Expected git-tree-sha1:   d61f806c76b57e54f343634c5219d00d4c81b077
    Calculated git-tree-sha1: 1[351](https://github.com/JuliaLang/PackageCompiler.jl/actions/runs/4730708525/jobs/8394765063?pr=804#step:5:354)b831192db9091d97e9b4bc84231ade05d210
```

[^1]:https://github.com/JuliaLang/PackageCompiler.jl/actions/runs/4730708525/jobs/8394765063?pr=804#step:5:197

**Comment by KristofferC** [comment]
> JULIA_CPU_TARGETS are ignored while building sysimage 1.9-rc2

Is there an upstream issue regarding this?

**Comment by KristofferC** [comment]
The CI error seems relevant or?

```
ERROR: More than one command line CPU targets specified without a `--output-` flag specified
PackageCompiler.jl: Error During Test at /home/runner/work/PackageCompiler.jl/PackageCompiler.jl/test/runtests.jl:36
  ```

**Comment by ven-k** [comment]
- The `ERROR: More than one command line CPU targets specified without a `--output-` flag specified` : this [comment](https://github.com/JuliaLang/julia/pull/48809#issue-1600966166) and #790 describe the issue.
- https://github.com/JuliaLang/julia/pull/48809 fixes that. But it isn't part of 1.9.0-rc2. Rn, it's enlisted here: https://github.com/JuliaLang/julia/pull/49302.
-
- However, https://github.com/JuliaLang/julia/pull/48809 doesn't fix the failing case of `JULIA_CPU_TARGET`. See this [comment](https://github.com/JuliaLang/julia/pull/48809#issuecomment-1505546852). (I'll pop that into its own issue)

**Pull request merged**
