### PR TITLE
only bundle libraries that are needed

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Comment by KristofferC** [comment]
I think this should be ready to go.

**Comment by sloede** [comment]
Out of curiosity, what will this PR being to PC.jl? From the title I assume it will improve somehow which libraries are bundled with a sysimage, but I can't tell from looking at the code 😬

**Comment by KristofferC** [comment]
It wil:

- Only bundle libraries for jlls that are actually used in the resulting sysimage
- It will fix https://github.com/JuliaLang/PackageCompiler.jl/issues/725.

**Comment by sloede** [comment]
> It will:
> 
> * Only bundle libraries for jlls that are actually used in the resulting sysimage
> * It will fix [too much stuff generated by default #725](https://github.com/JuliaLang/PackageCompiler.jl/issues/725).

Great, thanks!

**Pull request merged**
