### PR TITLE
Update build process with better placed info messages

### PR DESCRIPTION
**Pull request by asinghvi17**

### CODE REVIEW

**Comment by kdheepak** [comment]
Related to https://github.com/JuliaLang/PackageCompiler.jl/issues/185

**Comment by SimonDanisch** [comment]
Ok, while we're at it, should we add some simple install instructions for linux & osx?
e.g:
"""
Try `sudo apt-get install gcc` on linux, and XXXXXXXXXXXXXX on osx
"""
Is there a simple command to install gcc on osx?

**Comment by kdheepak** [comment]
`brew install gcc`

**Comment by asinghvi17** [comment]
@SimonDanisch this should be GTM, sorry for the 500 pings :D

**Comment by SimonDanisch** [comment]
Thanks!

**Pull request merged**
